import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { 
  Loader2, 
  AlertCircle, 
  ArrowRight, 
  CheckCircle2, 
  BookOpen, 
  XCircle,
  TrendingUp,
  MessageSquare
} from 'lucide-react';

export const InterviewResultPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [data, setData] = useState<any>(null);
  const [generatingPlan, setGeneratingPlan] = useState(false);

  useEffect(() => {
    const loadResult = async () => {
      if (!id) return;
      try {
        setLoading(true);
        const res = await api.getInterviewById(id);
        setData(res);
      } catch (err: any) {
        console.error(err);
        setErrorMsg('Failed to load interview report card details.');
      } finally {
        setLoading(false);
      }
    };
    loadResult();
  }, [id]);

  const handleGenerateStudyPlan = async () => {
    if (!id) return;
    try {
      setGeneratingPlan(true);
      const plan = await api.createStudyPlan(id);
      navigate(`/study-plan?activePlanId=${plan.id}`);
    } catch (err: any) {
      console.error(err);
      alert(err.message || 'Failed to generate study plan.');
    } finally {
      setGeneratingPlan(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[500px]">
        <div className="flex flex-col items-center">
          <div className="w-10 h-10 border-4 border-brand-500/20 border-t-brand-500 rounded-full animate-spin"></div>
          <p className="mt-4 text-gray-400 text-sm">Compiling assessment scorecard...</p>
        </div>
      </div>
    );
  }

  if (errorMsg || !data) {
    return (
      <div className="flex items-center gap-3 p-5 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 max-w-2xl mx-auto">
        <AlertCircle className="w-6 h-6 flex-shrink-0" />
        <p className="font-medium">{errorMsg || 'Interview session details missing.'}</p>
      </div>
    );
  }

  const { session, questions, answers } = data;

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Page Title Header */}
      <div>
        <h1 className="text-3xl font-black text-white tracking-tight">Final Mock Interview Report</h1>
        <p className="text-gray-400 text-sm mt-1">
          Review your scorecard, read the coach's feedback, and generate a customized study schedule.
        </p>
      </div>

      {/* Main Report Card Card */}
      <div className="bg-gradient-to-br from-[#0d1222]/80 via-[#0d1222]/40 to-transparent border border-gray-800 rounded-3xl p-8 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-brand-500/5 rounded-full blur-[100px] pointer-events-none"></div>

        {/* Top metrics summary row */}
        <div className="flex flex-col md:flex-row items-center justify-between gap-8 border-b border-gray-800 pb-8">
          <div className="flex items-center gap-6">
            <div className="flex flex-col items-center justify-center w-24 h-24 rounded-full bg-brand-500/10 border border-brand-500/30 text-brand-400 font-black text-3xl shadow-lg shadow-brand-500/5">
              {session.overall_score}%
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider bg-brand-500/10 border border-brand-500/25 text-brand-400 px-2.5 py-1 rounded-md">
                {session.performance_level || 'Completed'}
              </span>
              <h2 className="text-xl font-bold text-white mt-2">{session.topic} Core Assessment</h2>
              <p className="text-xs text-gray-500">
                {session.target_role} • {session.difficulty} • Generated by Gemini
              </p>
            </div>
          </div>

          <button
            onClick={handleGenerateStudyPlan}
            disabled={generatingPlan}
            className="w-full md:w-auto bg-gradient-to-r from-brand-600 to-violet-600 hover:from-brand-500 hover:to-violet-500 text-white font-bold text-sm px-6 py-4 rounded-xl border border-brand-500/30 transition shadow-lg shadow-brand-600/25 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
          >
            {generatingPlan ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                <span>Generating Study Plan...</span>
              </>
            ) : (
              <>
                <BookOpen className="w-5 h-5" />
                <span>Generate 7-Day Study Plan</span>
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>
        </div>

        {/* Detailed summaries split */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 py-8 border-b border-gray-800">
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
              <TrendingUp className="w-4 h-4 text-brand-400" /> Technical Competence Summary
            </h3>
            <p className="text-sm text-gray-300 leading-relaxed">{session.technical_summary}</p>
          </div>
          <div className="space-y-2">
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
              <MessageSquare className="w-4 h-4 text-brand-400" /> Communication Review
            </h3>
            <p className="text-sm text-gray-300 leading-relaxed">{session.communication_summary}</p>
          </div>
        </div>

        {/* Lists: Strong areas, Weak areas, Revision topics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-8">
          {/* Strong areas */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4" /> Strong Areas
            </h4>
            <ul className="list-disc list-inside text-sm text-gray-300 space-y-1.5">
              {session.strong_areas?.map((item: string, idx: number) => (
                <li key={idx} className="leading-relaxed">{item}</li>
              ))}
            </ul>
          </div>

          {/* Weak areas */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
              <XCircle className="w-4 h-4" /> Weak Areas / Gaps
            </h4>
            <ul className="list-disc list-inside text-sm text-gray-300 space-y-1.5">
              {session.weak_areas?.map((item: string, idx: number) => (
                <li key={idx} className="leading-relaxed">{item}</li>
              ))}
            </ul>
          </div>

          {/* Topics to revise (exactly 3) */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-brand-400 uppercase tracking-wider flex items-center gap-1.5">
              <BookOpen className="w-4 h-4" /> Recommended Revision
            </h4>
            <ul className="list-decimal list-inside text-sm text-gray-300 space-y-1.5">
              {session.topics_to_revise?.map((item: string, idx: number) => (
                <li key={idx} className="leading-relaxed font-semibold">{item}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Coach encouraging message */}
        {session.final_message && (
          <div className="mt-8 p-5 bg-brand-500/5 border border-brand-500/10 rounded-2xl">
            <p className="text-xs font-bold text-brand-400 uppercase tracking-wider mb-1">Coach's Final Remarks</p>
            <p className="text-sm text-gray-300 leading-relaxed italic">"{session.final_message}"</p>
          </div>
        )}
      </div>

      {/* Accordion list of all session questions & feedbacks */}
      <div className="space-y-4">
        <h3 className="text-xl font-bold text-white">Detailed Questions Breakdown</h3>
        <div className="space-y-6">
          {questions.map((q: any) => {
            const ans = answers.find((a: any) => a.question_id === q.id);
            return (
              <div key={q.id} className="bg-[#0d1222]/40 border border-gray-800 rounded-3xl p-6 md:p-8 space-y-5">
                <div className="flex items-center justify-between border-b border-gray-900 pb-4">
                  <span className="text-xs font-semibold text-gray-400">Question {q.question_order}</span>
                  {ans && (
                    <span className="text-sm font-bold text-brand-400 bg-brand-500/10 px-3 py-1 rounded-md border border-brand-500/15">
                      Score: {ans.score} / 10
                    </span>
                  )}
                </div>

                <div className="space-y-2">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-gray-500">Question Prompt</h4>
                  <p className="text-base text-white font-bold leading-relaxed">{q.question}</p>
                </div>

                {ans && (
                  <>
                    <div className="space-y-2">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-gray-500">Your Answer</h4>
                      <p className="text-sm text-gray-400 italic">"{ans.student_answer}"</p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-gray-900">
                      <div className="space-y-1">
                        <h5 className="text-xs font-bold text-brand-400 uppercase tracking-wider">Technical Review</h5>
                        <p className="text-sm text-gray-300 leading-relaxed">{ans.technical_feedback}</p>
                      </div>
                      <div className="space-y-1">
                        <h5 className="text-xs font-bold text-brand-400 uppercase tracking-wider">Communication Feedback</h5>
                        <p className="text-sm text-gray-300 leading-relaxed">{ans.communication_feedback}</p>
                      </div>
                    </div>
                  </>
                )}
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};
